BAD_WORDS = [
    "violación", "violador", "violar", "vi0lar", "v1olar",
    "incesto", "pederastia", "pedo", "abuso", "abusar",
    "violando", "violada", "pornografía infantil",
    "menor", "niño", "niña", "abuso infantil", "violar niños","f0llar",
  "fo11ar",
  "f0ll4r",
  "f0ll@r",
  "f*llar",
  "f0ll-ar",
  "f0ll.r",
  "f0ll4rX",
  "foll4r_",
  "foLL4r",
  "f0lL4r",
  "f0|lar",
  "f°llar",
  "f0l|ar",
  "f0ll4rXX",
  "f0l1ar",
  "f0l!ar",
  "f0l-l4r",
  "fol-l4r",
  "foll4rZ",
  "f0LL4R",
  "f0lLar~",
  "foll4r!!",
  "f0ll@r#",
  "f0l|_ar",
  "f0ll4r??",
  "f0ll4rrr",
  "foll_r",
  "f0ll_r",
  "f0ll4_r",
  "f0l1arX",
  "f0ll4r-test",
  "f0ll4r.mock",
  "f0ll4r.fake",
  "f0ll4r.sim",
  "f0ll4r-obf",
  "f0ll4r-enc", "follar niños"
]